### PR TITLE
dj-rest-auth setup

### PR DESCRIPTION
**Pull request by osadolortech**

### CODE REVIEW

**Comment by iamr0b0tx** [comment]
I am not reviewing this until you get a better branch name

**Review by iamr0b0tx — CHANGES_REQUESTED** [review]
I am not reviewing this until it has a better branch name

**Comment by osadolortech** [comment]
Ok sir, but I can’t edit branch sir, my next pull request will get a better
branch name sir, I’m sorry sir

**Comment by iamr0b0tx** [comment]
No. go and figure it out

**Pull request merged**
